// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmkxpohsoxogtvdyopmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBta3hwb2hzb3hvZ3R2ZHlvcG1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDg3OTEsImV4cCI6MjA2NTQ4NDc5MX0.Nm4IOIE9RQggrL42h2qAhj-y52hXhE_aZeoaXCs9qxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);